config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :elections, only: %i[index show edit update] do
    resources :restaurants, only: %i[new create show] do
      resources :votes, only: %i[new create edit update destroy]
    end
    resources :user_elections, only: %i[create]
    member do
      get :results
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/election.rb
class Election < ApplicationRecord
  belongs_to :user
  has_many :restaurants, dependent: :destroy
  has_many :votes, through: :restaurants
  has_many :user_elections, dependent: :destroy
  has_one_attached :photo
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :election
  has_many :votes
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :votes
  has_many :elections
  has_many :user_elections
end

app/models/user_election.rb
class UserElection < ApplicationRecord
  belongs_to :user
  belongs_to :election

  validates :election, uniqueness: { scope: :user }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  validates :flavour, :crunchiness, :appearance, :meat_ratio,
            numericality: { only_integer: true,
                            greater_than_or_equal_to: 0,
                            less_than_or_equal_to: 10,
                            message: "Só números inteiros entre 0 e 10"}
  validates :restaurant, uniqueness: { scope: :user, message: "já votaste no croquete deste restaurante" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  before_action :authenticate_user!
  def index
    @elections = Election.all
  end

  def show
    @election = Election.find(params[:id])
    # redirect_to results_election_path(@election) if @election.finished
  end

  def edit
    @election = Election.find(params[:id])
  end

  def update
    @election = Election.find(params[:id])
    if @election.update(election_params)
      redirect_to election_path(@election)
    else
      render :edit
    end
  end

  def results
    set_election
    if current_user == @election.user
      @election = Election.find(params[:id])
      @restaurants = @election.restaurants
      @restaurants.each do |restaurant|
        restaurant_average(restaurant)
      end
      finish_election(@election)
      @election.save
    end
    unless @election.finished
      redirect_to election_path(@election)
    end
  end

  private

  def finish_election(election)
    election.finished = true
  end

  def restaurant_average(restaurant)
    unless restaurant.votes.empty?
      crunchiness = []
      flavour = []
      meat_ratio = []
      appearance = []
      restaurant.votes.each do |vote|
        crunchiness << vote.crunchiness
        flavour << vote.flavour
        meat_ratio << vote.meat_ratio
        appearance << vote.appearance
      end
      crunchiness = crunchiness.inject{ |sum, el| sum + el }.to_f / crunchiness.size
      flavour = flavour.inject{ |sum, el| sum + el }.to_f / flavour.size
      meat_ratio = meat_ratio.inject{ |sum, el| sum + el }.to_f / meat_ratio.size
      appearance = appearance.inject{ |sum, el| sum + el }.to_f / appearance.size
      restaurant.rating = ((crunchiness * 0.25) + (flavour * 0.35) + (meat_ratio * 0.15) + (appearance * 0.25)).round(2)
      restaurant.save
    end
  end

  def set_election
    @election = Election.find(params[:id])
  end

  def election_params
    params.require(:election).permit(:name, :date, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def new
    @restaurant = Restaurant.new
    set_election
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    set_election
    @restaurant.election = @election
    if @restaurant.save
      redirect_to election_path(@election)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :photo)
  end

  def set_election
    @election = Election.find(params[:election_id])
  end
end

app/controllers/user_elections_controller.rb
class UserElectionsController < ApplicationController
  def create
    @election = Election.find(params[:election_id])
    if check_password(params[:password])
      @user_election = UserElection.new(user: current_user, election: @election)
      @user_election.save
      redirect_to election_path(@election)
    else
      flash[:alert] = "Password errada"
      redirect_to elections_path
    end
  end

  private

  def check_password(password)
    @election.password == password
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new
    @vote = Vote.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @vote = Vote.new(vote_params)
    restaurant = Restaurant.find(params[:restaurant_id])
    @vote.restaurant = restaurant
    @vote.user = current_user
    if @vote.save
      redirect_to election_path(restaurant.election)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
    @vote = Vote.find(params[:id])
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def update
  end

  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy
    redirect_to election_path(@vote.restaurant.election)
  end

  private

  def vote_params
    params.require(:vote).permit(:crunchiness, :flavour, :appearance, :meat_ratio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/elections/_modal.html.erb
<div class="modal fade" id="Modal<%=index%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <form action="/elections/<%=election.id%>/user_elections" method="post">
          <label for="password">Password:</label>
          <input type="password" name="password" id="password">

      </div>
      <div class="modal-footer justify-content-center">
          <input type="submit" value="Submeter">
        </form>
      </div>
    </div>
  </div>
</div>

app/views/elections/_modal_vote.html.erb
<div class="modal fade" id="Modal<%=index%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <%= simple_form_for [election, restaurant, Vote.new] do |f| %>
          <%= f.input :crunchiness, label: "Crocância", as: :range, input_html:{ min:"0", max:"10"}%>
          <%= f.input :flavour, label: "Sabor", as: :range, input_html:{ min:"0", max:"10"}%>
          <%= f.input :appearance, label: "Aspecto", as: :range, input_html:{ min:"0", max:"10"}%>
          <%= f.input :meat_ratio, label: "Rácio de carne/pão", as: :range, input_html:{ min:"0", max:"10"}%>
        <div class="d-flex justify-content-center">
          <%= f.submit "Vota" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/elections/edit.html.erb
<%= simple_form_for @election do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.button :submit %>
<% end %>

app/views/elections/index.html.erb
<div class="container p-3">
  <h1 class="text-2xl text-[#55AD9B]">Concursos a decorrer:</h1>
  <div class="grid-container pt-1">
    <% @elections.order(created_at: :asc).each_with_index do |election, index| %>
      <div class="grid-item">
        <% if election.user_elections.where(user: current_user).any? || election.user == current_user %>
          <%= link_to election_path(election) do %>
            <div class="election-card">
              <h5 class="election-name"><%= election.name %></h5>
              <div class="card-img" style="<%= election.photo.attached? ? "background-image:url(#{url_for election.photo})" : "" %>"></div>
            </div>
          <% end %>
          <% else %>
            <div class="election-card" data-bs-toggle="modal" data-bs-target="#Modal<%=index%>">
              <h5 class="election-name"><%= election.name %></h5>
              <div class="card-img" style="<%= election.photo.attached? ? "background-image:url(#{url_for election.photo})" : "" %>"></div>
            </div>
            <%= render 'modal', election: election, index: index %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/elections/results.html.erb
<div class="container">
  <div class="title-results d-flex flex-column justify-content-center align-items-center">
    <h1>Esta eleição terminou!</h1>
    <h3>O Vencedor é <strong><%= @election.restaurants.order(rating: :desc).first.name %></strong></h3>
  </div>
  <div class="cards-container">
    <p><%= "Não podes votar neste concurso. Ainda não te inscreveste 🤷🏼" unless @election.user_elections.where(user: current_user).any? || @election.user == current_user %></p>
    <ol style="padding:0; margin:0">
      <% @election.restaurants.order(rating: :desc).each_with_index do |restaurant, index| %>
        <% if index == 0 %>
          <div class="restaurant-card">
            <li class="restaurant-li <%= 'winner' if index == 0 %>"
            style="background-image: url(<%= cl_image_path restaurant.photo.key %>);">Croquete do <%= restaurant.name %></li>
          </div>
        <% end %>
      <% end %>
    </ol>
  </div>

  <h3 class="text-center mt-4"><strong>Classificação Final</strong></h3>
  <table>
    <tbody>
      <% @election.restaurants.order(rating: :desc).each_with_index do |restaurant, index| %>
        <tr>
          <td><%= restaurant.name %></td>
          <td class="text-center"><%= restaurant.rating %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="btn-container d-flex justify-content-center" data-controller="change-button">
  <button class="interactive-button mt-4" id="myButton" data-action="click->change-button#fire">Concordas?</button>
</div>

app/views/elections/show.html.erb
<div class="container">
  <% unless @election.finished %>
    <h1 class="text-center"><%= @election.name %></h1>
    <div class="cards-container">
      <p><%= "Não podes votar neste concurso. Ainda não te inscreveste 🤷🏼" unless @election.user_elections.where(user: current_user).any? || @election.user == current_user %></p>
      <ul style="padding:0; margin:0">
        <% @election.restaurants.each_with_index do |restaurant, index| %>
          <div class="restaurant-card">
            <li class="restaurant-li"
            style="background-image: url(<%= cl_image_path restaurant.photo.key %>);"
            data-bs-toggle="modal"
            <% if restaurant.votes.where(user: current_user).empty? %>
            data-bs-target="#Modal<%=index%>"
            <% end %>>Croquete do <%= restaurant.name %></li>
            <% unless restaurant.votes.where(user: current_user).empty? %>
              <div class="vote-options">
                <%= link_to  "Editar | ", edit_election_restaurant_vote_path(restaurant.election, restaurant, restaurant.votes.where(user: current_user).last) %>
                <%= link_to  "| Apagar", election_restaurant_vote_path(restaurant.election, restaurant, restaurant.votes.where(user: current_user).last),
                data: {turbo_method: :delete, turbo_confirm: "Queres mesmo apagar este voto?"} %>
              </div>
            <% end %>
            <hr style="width:120%; margin-left:-15%;">
          </div>
            <%= render 'modal_vote', election: restaurant.election, restaurant: restaurant, index: index %>
        <% end %>
      </ul>
    </div>
  <% else %>
    <div class="finished-election-container container d-flex flex-column align-items-center">
      <h1 class="text-center"><%= @election.name %> já terminou!</h1>
      <br>
      <h3>Checka aqui os resultados</h3>
      <br>
      <%= link_to "CHECKAR", results_election_path(@election), class:"btn btn-primary mb-3" %>
      <br>
    </div>
  <% end %>
</div>

<% if @election.user == current_user %>
  <div class="div text-center">
    <div class="mb-3">
      <%= link_to  "Add Restaurant", new_election_restaurant_path(@election) %>
    </div>
    <div class="mb-3">
      <a href="/elections/<%=@election.id%>/results" onclick="return confirm('Queres mesmo terminar esta eleição?')">Terminar <%= @election.name %></a>
    </div>
    <div>
      <%= link_to  "Edit Election", edit_election_path(@election)%>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tour Do Croquete</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.2/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://kit.fontawesome.com/06cc570cb5.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%
=begin%>
 <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
<%
=end%>
  </head>

  <body>
  <% unless action_name == "home" %>
    <%= render "shared/navbar" %>
  <% end %>
  <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container d-flex flex-column align-items-center justify-content-center">
  <h1 class="text-5xl text-[#55AD9B] font-extrabold mt-4">TOUR DO CROQUETE</h1>
    <p class="text-s text-[#55AD9B] font-extrabold mt-2">( Clica aí no croquete )</p>
    <%= link_to elections_path do %>
      <div class="home-img">
        <img src='https://res.cloudinary.com/db80w7hs9/image/upload/v1688813539/development/m0rom1syycemqfm9lzjtf5e8gt5a.png',
        class='w-100',
        style= 'max-height: 500px;'>
      </div>
    <% end %>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for [@election, @restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar ">
  <div class="flex-1">
    <%= link_to elections_path, class: "navbar-brand" do %>
      <%= image_tag 'logo.png', class:"navbar-logo" %>
      <div class="flex-1 flex items-center">
        <p class="btn btn-ghost text-l flex items-end text-bold text-[#55ad9b]">Tour do Croquete</p>
      </div>
    <% end %>
  </div>
  <div class="flex-none">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-link nav-link" do %>
            <i class="fa-solid fa-arrow-right-from-bracket"></i>
          <% end %>
        </li>
      <% else %>
        <% end %>
    </ul>
  </div>
</div>

app/views/votes/_form.html.erb
<%= simple_form_for [election, restaurant, vote] do |f| %>

  <%= f.input :crunchiness, as: :range, input_html:{ min:"0", max:"10"}%>
  <%= f.input :flavour, label: "Sabor" %>
  <%= f.input :appearance, label: "Aspecto" %>
  <%= f.input :meat_ratio, label: "Rácio de carne/pão" %>
  <%= f.submit %>
<% end %>

app/views/votes/edit.html.erb
<%= render 'form', election: @restaurant.election, restaurant: @restaurant, vote: @vote %>

app/views/votes/new.html.erb
<%= render 'form',  election: @restaurant.election, restaurant: @restaurant, vote: @vote %>